app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__= 'users'
    id=db.Column(db.Integer,primary_key =True)
    username = db.Column(db.String(255))
    email=db.Column(db.String(255),unique=True,index = True)
    pass_hash =db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password Attribute')

    @password.setter
    def password(self,password):
        self.pass_hash =generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.pass_hash,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):

         return f'User {self.username}'

class Comments(db.Model):
    __tablename__ ='comments'
    id = db.Column(db.Integer,primary_key= True)
    name=db.Column(db.String(255))
    pitch=db.relationship('Pitch',backref='comments',lazy='dynamic')

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls):
        '''
        Function that queries the Groups Table in the database and returns all the information from the Groups Table
        Returns:
            groups : all the information in the groups table
        '''

        comments = Comments.query.all()

        return comments


class Pitch(db.Model):
    __tablename__='pitches'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(255))
    description=db.Column(db.String)
    like = db.Column(db.Integer)
    dislike = db.Column(db.Integer)
    comments_id =db.Column(db.Integer,db.ForeignKey("comments.id"))


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

        
    @classmethod
    def get_pitches(cls):
        '''
        gets pitches from the database
        '''
        pitches=Pitch.query.all()
        return pitches

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    title = StringField('Enter pitch category',validators=[Required()])
    description= TextAreaField('pitch description')
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    name = TextAreaField('Enter comment.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE


login_manager = LoginManager()
login_manager.session_protection ='strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()



#initialize app
def create_app(config_name):
    app = Flask(__name__)
    app.debug = True

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,redirect,url_for,request
from . import main
from flask_login import login_required,login_user,logout_user
from ..models import Pitch,Comments
from .forms import PitchForm,CommentForm
from ..import db

@main.route('/')
def index():
    title = 'Home'

    pitches = Pitch.get_pitches()
    comments=Comments.get_comments()

    return render_template('index.html' ,title=title, pitches=pitches,comments=comments)

@main.route('/pitch/new',methods=['GET','POST'])
@login_required
def new_pitch():
    form= PitchForm()
    if form.validate_on_submit():
        title=form.title.data
        description=form.description.data
        like=0
        dislike=0
        new_pitch=Pitch(title=title,description=description,like=like,dislike=dislike)
        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    title= 'Pitches'
    return render_template('new_pitch.html',pitch_form=form)

@main.route('/comment/new/', methods=['GET','POST'])
@login_required
def new_comment():

    '''
    View new comment route function that returns a page with a form to create a pitch for the specified category
    '''
    comments = Comments.query.all()
    form =CommentForm()
    if form.validate_on_submit():
        name=form.name.data
        new_comment=Comments(name=name)
        new_comment.save_comment()

        return redirect(url_for('.index'))

    title = "New Comment"
    return render_template('new_comment.html', title=title, form=form,comments=comments)

@main.route('/pitch_review/<int:id>',methods=['GET','POST'])

def pitch_review(id):
    pitches=Pitch.query.get_or_404(id)
    if request.args.get("like"):
        pitches.like = pitches.like+1

        db.session.add(pitches)
        db.session.commit()

        return redirect("/pitch_review/{pitch_id}".format(pitch_id=pitches.id))

    elif request.args.get("dislike"):
        pitches.dislike=pitches.dislike+1

        db.session.add(pitches)
        db.session.commit()

        return redirect("/pitch_review/{pitch_id}".format(pitch_id=pitches.id))

    title= 'Pitches'
    return render_template('pitch_review.html',pitches=pitches)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<!-- Navbar block-->

	{% block navbar %}
		{% include 'navbar.html' %}

	{% endblock %}

	{%block styles %}
	{{super()}}

	<!--Importing the simple mde css and js files  -->

	{{ simplemde.css}}
	{{ simplemde.js }}

	{% endblock %}
	</body>

</html>

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
<h1>One minute pitch</h1>
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
{% endblock %}
{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Srisakdi');
     h2{            display: block;
            font-family: 'Srisakdi', 'sans-serif';
            color: blue;
            font-size: 40px;
            font-weight: 1000;
            
          }
          ul {
            font-family: 'Srisakdi',  sans-serif;
          }
          body{
            background-image: url('/static/css/photo/abstract-attractive-backdrop-988872.jpg')
          }
          a{            display: block;
                    font-family: 'Srisakdi', 'sans-serif';
                    color: green;
                    font-size: 30px;
                    font-weight: 1000;
                    text-align: center;
                  }
          
</style>

    <title> {{ title }} </title>

    <div class="container">

        <div class="row">            
            <h2 class="pitch-header" >
                One Minute Pitches
            </h2>
                
        </div>
        <br><br><br>
        <div class="row">
            
            <div class="col-md-4 col-lg-4"> 
                <h2 class="pitch-create">
                    <a href="/pitch/new">
                        Create New Pitch
                    </a>
                </h2>
                
            </div> 

        </div>
        <hr>

        <ul class="list-unstyled">

            {{ macro.displayPitchList(pitches) }}

        </ul>

        <ul class="list-unstyled">
            {{ macro.displayCommentList(comments) }}
        </ul>



        <hr>


  </div>


{% endblock %}

app/templates/macros.html
{% macro displayPitchList(pitches) %}


    {% for pitch in pitches %}
        <div class="row">

            <div class="col-md-2 col-lg-2">

            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 well pitch-well">

                <li class="text-center">
                    <h2>{{pitch.title}}</h2>
                    <h3>{{pitch.description}}</h3>
                    <a href ="/pitch_review/{{pitch.id}}?like=1">Like: {{pitch.like}}</a>
                    <a href ="/pitch_review/{{pitch.id}}?dislike=1">Dislike: {{pitch.dislike}}</a>  
                    <h3 class="comment-create">
                        <a href="{{url_for('main.new_comment')}}">Add Comment</a>                                                        
                    </h3>
                </li>

            </div>

            <div class="col-md-2 col-lg-2">

            </div>

        </div>

    {% endfor %}
    {% endmacro %}

    {% macro displayCommentList(comments) %}


        {% for comment in comments %}
            <div class="row">

                <div class="col-md-2 col-lg-2"></div>
                
                <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 well comment-well">

                    <li>

                        <h4 class="comment-content">
                          {{comment.name}}
                        </h4>

                    </li>

                </div>

                <div class="col-md-2 col-lg-2">

                </div>

            </div>

        {% endfor %}

{% endmacro %}

app/templates/navbar.html
<style>
    .container-fluid{
    background-color: gray;
      }
    </style>
    <div class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"> What's Your Pitch </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>

                        {% if current_user.is_authenticated %}
                        <li style="color:blue;">{{current_user.username}}</li>
                        <li><a href="{{url_for('main.index',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                      {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                      {% endif %}  

                </div>
    
            </div>
    </div>

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
    <title> {{ title }} </title>

    <div class="container">
        
        <div class="row">

            <div class="col-md-2 col-lg-2">

            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">
            
                {{ wtf.quick_form(pitch_form) }}

            </div>

            <div class="col-md-2 col-lg-2">

            </div>

        </div>
    </div>
{% endblock %}

app/templates/newpitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
    <title> {{ title }} </title>

    <div class="container">
        
        <div class="row">

            <div class="col-md-2 col-lg-2">

            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">
            
                {{ wtf.quick_form(pitch_form) }}

            </div>

            <div class="col-md-2 col-lg-2">

            </div>

        </div>
    </div>
{% endblock %}

app/templates/pitch_review.html
{% extends 'base.html'%}
{% block content %}


    <div class="col-md-2 col-lg-2">

    </div>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Srisakdi');
         h2{            display: block;
                font-family: 'Srisakdi', 'Trebuchet MS';
                color: black;
                font-size: 40px;
                font-weight: 1000;
                text-align: center;
              }
              ul {
                font-family: 'Srisakdi',  Georgia;
              }
              body{
                background-image: url('/static/css/photo/abstract-attractive-backdrop-988872.jpg')
              }
        </style>
</div>


        <style>
            @import url('https://fonts.googleapis.com/css?family=Srisakdi');
             a{            display: block;
                    font-family: 'Srisakdi', 'Trebuchet MS';
                    color: black;
                    font-size: 20px;
                    font-weight: 1000;
                    text-align: center;
                  }
                  
            </style>

    <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 well pitch-well">

        <li class="text-center">
            <h2>{{pitches.title}}</h2>
            <h2>{{pitches.description}}</h2>
            <a href ="/pitch_review/{{pitches.id}}?like=1">Like: {{pitches.like}}</a>
            <a href ="/pitch_review/{{pitches.id}}?dislike=1">Dislike: {{pitches.dislike}}</a>
        </li>

    </div>

    <div class="col-md-2 col-lg-2">

    </div>

</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying Username -->
    <div class="col-md-4">
      <h3> {{user.username | capitalize}}</h3>
      <!-- Displaying user bio -->
      {% if user.bio %}
        <p>{{user.bio}}</p>
      {% else %}
        <p> {{user.username|capitalize}} has no bio </p>
      {% endif %}

      {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
      {% endif %}
    </div>

    <!-- Displaying profile photo -->
    <div class="col-md-4">
      {% if user.profile_pic_path %}
        <!-- <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> -->
      {% else %}
        <p>No profile picture</p>
      {% endif %}

      {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
          <input type="file" name="photo" class="form-control" required>
          <input type="submit">
        </form>
      {% endif %}

    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}